"""
Step 5: Top 3 Priorities
Identify top 3 priorities for next month based on impact and timeline
"""
from typing import Dict, Any
import pandas as pd
from .base import BaseStep, StepResult
from .. import config


class Step5TopPriorities(BaseStep):
    """
    Step 5: Identify Top 3 Priorities

    Logic:
    1. Sort by impact uplift (high to low)
    2. Then filter by timeline (near to far)
    3. Take top 3
    """

    @property
    def name(self) -> str:
        return "Step 5: Top 3 Priorities"

    @property
    def description(self) -> str:
        return "Identify top 3 priorities for next month"

    def execute(self, month: int, year: int, context: Dict[str, Any]) -> Dict[str, Any]:
        """Execute step 5"""
        next_month, next_year = self.data_source.get_next_month(month, year)
        self.log(f"Finding top 3 priorities for {config.get_month_name(next_month)} {next_year}")

        # Get initiatives data
        initiatives_df = context.get("initiatives_data")

        if initiatives_df is None or initiatives_df.empty:
            return StepResult(
                success=False,
                error="No initiatives data available"
            ).__dict__

        # Parse impact scores. A "priority for next month" must still be
        # actionable, so skip section rows and already-finished / dropped items.
        excluded_status = {"live", "done", "deprioritized"}
        section_names = {"strategic unlock", "incremental improvements"}
        initiatives_with_impact = []

        for _, row in initiatives_df.iterrows():
            name = str(row.get("Initiative Names", "")).strip()
            status = str(row.get("Status", "")).strip()
            if not name or name.lower() in section_names:
                continue
            if status.lower() in excluded_status:
                continue

            impact = self._parse_impact_score(row.get("Expected impact", ""))
            # Rule 16: priorities are HIGH-impact initiatives that are delayed /
            # at-risk (need attention), not on-track ones coasting along.
            at_risk = 1 if status.lower() in {"delay", "not started"} else 0
            initiatives_with_impact.append({
                "name": name,
                "timing": row.get("Timing", ""),
                "status": status,
                "impact": impact,
                "at_risk": at_risk,
                "pic": row.get("PIC", ""),
                "expected_impact": row.get("Expected impact", "")
            })

        # Convert to DataFrame for easier sorting
        df = pd.DataFrame(initiatives_with_impact)

        # Rank: at-risk first (Rule 16), then higher impact, then nearer timeline.
        df = df.sort_values(by=["at_risk", "impact", "timing"],
                            ascending=[False, False, True])

        # Take top 3
        top_3 = df.head(3)

        # Generate markdown content
        md_content = self._generate_markdown(top_3, next_month, next_year)

        # Save to file
        output_file = config.TOP_PRIORITIES_DIR / f"Top 3 priorities for month {next_month}-{next_year}.md"
        output_file.write_text(md_content, encoding='utf-8')

        # Save to context
        context["top_3_priorities"] = top_3
        context["top_3_markdown"] = md_content

        self.log(f"Saved top 3 priorities to {output_file.name}", "success")

        return StepResult(
            success=True,
            data={"priorities": top_3.to_dict("records")},
            message=f"Top 3 priorities identified for {config.get_month_name(next_month)}"
        ).__dict__

    def _parse_impact_score(self, impact_str: str) -> float:
        """Parse impact score from impact string"""
        import re

        if pd.isna(impact_str):
            return 0

        # Look for +XXpp or +XX%
        matches = re.findall(r'\+(\d+)\s*(?:pp|%)', str(impact_str))
        if matches:
            return max([float(m) for m in matches])

        return 0

    def _generate_markdown(self, df: pd.DataFrame, month: int, year: int) -> str:
        """Generate markdown for top 3 priorities"""
        md = f"# Top 3 Priorities for {config.get_month_name(month)} {year}\n\n"
        md += f"Generated: {pd.Timestamp.now().strftime('%Y-%m-%d')}\n\n"
        md += "---\n\n"

        for idx, (_, row) in enumerate(df.iterrows(), 1):
            md += f"## {idx}. {row['name']}\n\n"
            md += f"- **Status**: {row['status']}\n"
            md += f"- **PIC**: {row['pic']}\n"
            md += f"- **Timing**: {row['timing']}\n"
            md += f"- **Expected Impact**: {row['expected_impact']}\n"
            md += f"- **Impact Score**: {row['impact']}\n\n"

        md += "---\n\n"
        md += "*Generated by Report Generate Agent*\n"

        return md


from datetime import datetime