"""
Step 6: Overall Progress Toward Annual Planning
Compare initiatives with annual planning and generate progress report
"""
from typing import Dict, Any
import pandas as pd
from .base import BaseStep, StepResult
from .. import config


class Step6AnnualProgress(BaseStep):
    """
    Step 6: Overall Progress Toward Annual Planning

    Compare current initiatives with annual planning:
    - On Track/Done: Mark as On Track/Done
    - Not started, Delay, Deprioritized: Add comments from details
    """

    @property
    def name(self) -> str:
        return "Step 6: Annual Planning Progress"

    @property
    def description(self) -> str:
        return "Compare with annual planning and generate progress report"

    def execute(self, month: int, year: int, context: Dict[str, Any]) -> Dict[str, Any]:
        """Execute step 6"""
        self.log(f"Generating annual progress for {config.get_month_name(month)} {year}")

        # Get data
        initiatives_df = context.get("initiatives_data")
        annual_df = self.data_source.get_annual_planning_data()

        if initiatives_df is None or initiatives_df.empty:
            return StepResult(
                success=False,
                error="No initiatives data available"
            ).__dict__

        # Separate Strategic Unlock and Incremental Improvements
        strategic = []
        incremental = []

        current_section = None

        for idx, row in initiatives_df.iterrows():
            name = str(row.get("Initiative Names", ""))

            # Detect section headers
            if "Strategic unlock" in name:
                current_section = "Strategic Unlock"
                continue
            elif "Incremental" in name:
                current_section = "Incremental Improvements"
                continue
            elif pd.isna(row.get("No")) or row.get("No") == "":
                continue

            status = row.get("Status", "")
            details = row.get("Details from that month", "")
            new_timing = row.get("New timing", "")

            item = {
                "No": row.get("No"),
                "Initiative": name,
                "Status": status,
                "Details": details if pd.notna(details) else "",
                "New Timing": new_timing if pd.notna(new_timing) else ""
            }

            if current_section == "Strategic Unlock":
                strategic.append(item)
            elif current_section == "Incremental Improvements":
                incremental.append(item)

        # Generate markdown
        md_content = self._generate_markdown(strategic, incremental, month, year)

        # Save to file
        output_file = config.OVERALL_PROGRESS_DIR / f"Overall progress {config.get_month_name(month)} {year}.md"
        output_file.write_text(md_content, encoding='utf-8')

        # Save to context (markdown + structured lists for the PDF)
        context["annual_progress_markdown"] = md_content
        context["annual_progress_strategic"] = strategic
        context["annual_progress_incremental"] = incremental

        self.log(f"Saved annual progress to {output_file.name}", "success")

        return StepResult(
            success=True,
            data={
                "strategic_count": len(strategic),
                "incremental_count": len(incremental)
            },
            message=f"Annual progress generated: {len(strategic)} strategic, {len(incremental)} incremental"
        ).__dict__

    def _generate_markdown(self, strategic: list, incremental: list, month: int, year: int) -> str:
        """Generate markdown for annual progress"""
        md = f"# Overall Progress Toward Annual Planning\n"
        md += f"## {config.get_month_name(month)} {year}\n\n"
        md += f"Generated: {pd.Timestamp.now().strftime('%Y-%m-%d')}\n\n"
        md += "---\n\n"

        # Strategic Unlock
        md += "## (i) Strategic Unlock\n\n"
        md += "| No | Initiative | Status | Comments |\n"
        md += "|----|------------|--------|----------|\n"

        for item in strategic:
            status = item["Status"]
            comments = self._get_comments(item)
            md += f"| {self._fmt_no(item['No'])} | {item['Initiative']} | {status} | {comments} |\n"

        # Incremental Improvements
        md += "\n## (ii) Incremental Improvements\n\n"
        md += "| No | Initiative | Status | Comments |\n"
        md += "|----|------------|--------|----------|\n"

        for item in incremental:
            status = item["Status"]
            comments = self._get_comments(item)
            md += f"| {self._fmt_no(item['No'])} | {item['Initiative']} | {status} | {comments} |\n"

        md += "\n---\n\n"
        md += "*Generated by Report Generate Agent*\n"

        return md

    @staticmethod
    def _fmt_no(no) -> str:
        """Render the initiative number without a trailing .0."""
        try:
            return str(int(float(no)))
        except (TypeError, ValueError):
            return str(no)

    def _get_comments(self, item: dict) -> str:
        """Generate comments based on status"""
        status = item["Status"]
        details = item.get("Details", "")
        new_timing = item.get("New Timing", "")

        if status in ["On Track", "Done", "Live"]:
            return f"[OK] {status}"
        elif status == "Delay":
            comments = f"[WARNING] Delayed"
            if new_timing:
                comments += f" - New timing: {new_timing}"
            if details:
                comments += f" - {details[:100]}"
            return comments
        elif status == "Not started":
            if details:
                return f"[INFO] {details[:100]}"
            return "Not yet started"
        elif status == "Deprioritized":
            if details:
                return f"? Deprioritized - {details[:100]}"
            return "Deprioritized"
        else:
            return status


from datetime import datetime